// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Modules.CRM.Infrastructure.Database;

#nullable disable

namespace Server.Modules.CRM.Infrastructure.Database.Migrations
{
    [DbContext(typeof(CRMDbContext))]
    [Migration("20250507214028_UpdateDocumentEntity")]
    partial class UpdateDocumentEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("crm")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Modules.CRM.Entities.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RepresentativeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Contracts", "crm");
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvoiceEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("NumberOfEmployees")
                        .HasColumnType("integer");

                    b.Property<string>("OHServicesRequired")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers", "crm");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "1 Acme Street, London",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@acme.example.com",
                            Industry = "Technology",
                            InvoiceEmail = "accounts@acme.example.com",
                            IsActive = true,
                            LastModifiedBy = 1,
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Acme Corp",
                            Notes = "Key client.",
                            NumberOfEmployees = 100,
                            OHServicesRequired = "Full OH Service",
                            Postcode = "AC1 2ME",
                            Site = "London",
                            Telephone = "01234 567890",
                            Website = "https://acme.example.com"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "2 Beta Road, Manchester",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Email = "contact@beta.example.com",
                            Industry = "Manufacturing",
                            InvoiceEmail = "finance@beta.example.com",
                            IsActive = true,
                            LastModifiedBy = 1,
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Beta Ltd",
                            Notes = "Annual contract.",
                            NumberOfEmployees = 50,
                            OHServicesRequired = "Health Surveillance",
                            Postcode = "BT2 3LT",
                            Site = "Manchester",
                            Telephone = "02345 678901",
                            Website = "https://beta.example.com"
                        },
                        new
                        {
                            Id = 3L,
                            Address = "3 Gamma Avenue, Birmingham",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hello@gamma.example.com",
                            Industry = "Logistics",
                            InvoiceEmail = "billing@gamma.example.com",
                            IsActive = true,
                            LastModifiedBy = 1,
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gamma Inc",
                            Notes = "Occasional work.",
                            NumberOfEmployees = 200,
                            OHServicesRequired = "Ad hoc assessments",
                            Postcode = "GM3 4IN",
                            Site = "Birmingham",
                            Telephone = "03456 789012",
                            Website = "https://gamma.example.com"
                        });
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Documents", "crm");
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("JobRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LineManager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees", "crm");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address1 = "1 Main St",
                            Address2 = "Apt 1",
                            Address3 = "",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1L,
                            DOB = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Email = "alice.smith@example.com",
                            FirstName = "Alice",
                            IsActive = true,
                            JobRole = "Manager",
                            LastModifiedBy = 1,
                            LastName = "Smith",
                            LineManager = "Bob Jones",
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Postcode = "EMP1 1AA",
                            Telephone = "07111 111111"
                        },
                        new
                        {
                            Id = 2L,
                            Address1 = "2 Main St",
                            Address2 = "Apt 2",
                            Address3 = "",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2L,
                            DOB = new DateTime(1985, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "IT",
                            Email = "bob.jones@example.com",
                            FirstName = "Bob",
                            IsActive = true,
                            JobRole = "Engineer",
                            LastModifiedBy = 1,
                            LastName = "Jones",
                            LineManager = "Carol White",
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Postcode = "EMP2 2BB",
                            Telephone = "07222 222222"
                        },
                        new
                        {
                            Id = 3L,
                            Address1 = "3 Main St",
                            Address2 = "Apt 3",
                            Address3 = "",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3L,
                            DOB = new DateTime(1992, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Email = "carol.white@example.com",
                            FirstName = "Carol",
                            IsActive = true,
                            JobRole = "Analyst",
                            LastModifiedBy = 1,
                            LastName = "White",
                            LineManager = "David Black",
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Postcode = "EMP3 3CC",
                            Telephone = "07333 333333"
                        },
                        new
                        {
                            Id = 4L,
                            Address1 = "4 Main St",
                            Address2 = "Apt 4",
                            Address3 = "",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1L,
                            DOB = new DateTime(1988, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Consulting",
                            Email = "david.black@example.com",
                            FirstName = "David",
                            IsActive = true,
                            JobRole = "Consultant",
                            LastModifiedBy = 1,
                            LastName = "Black",
                            LineManager = "Alice Smith",
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Postcode = "EMP4 4DD",
                            Telephone = "07444 444444"
                        },
                        new
                        {
                            Id = 5L,
                            Address1 = "5 Main St",
                            Address2 = "Apt 5",
                            Address3 = "",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2L,
                            DOB = new DateTime(1995, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Medical",
                            Email = "eve.green@example.com",
                            FirstName = "Eve",
                            IsActive = true,
                            JobRole = "Nurse",
                            LastModifiedBy = 1,
                            LastName = "Green",
                            LineManager = "Bob Jones",
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Postcode = "EMP5 5EE",
                            Telephone = "07555 555555"
                        },
                        new
                        {
                            Id = 6L,
                            Address1 = "6 Main St",
                            Address2 = "Apt 6",
                            Address3 = "",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3L,
                            DOB = new DateTime(1983, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Support",
                            Email = "frank.blue@example.com",
                            FirstName = "Frank",
                            IsActive = true,
                            JobRole = "Technician",
                            LastModifiedBy = 1,
                            LastName = "Blue",
                            LineManager = "Carol White",
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Postcode = "EMP6 6FF",
                            Telephone = "07666 666666"
                        },
                        new
                        {
                            Id = 7L,
                            Address1 = "7 Main St",
                            Address2 = "Apt 7",
                            Address3 = "",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1L,
                            DOB = new DateTime(1991, 7, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Advisory",
                            Email = "grace.brown@example.com",
                            FirstName = "Grace",
                            IsActive = true,
                            JobRole = "Advisor",
                            LastModifiedBy = 1,
                            LastName = "Brown",
                            LineManager = "David Black",
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Postcode = "EMP7 7GG",
                            Telephone = "07777 777777"
                        },
                        new
                        {
                            Id = 8L,
                            Address1 = "8 Main St",
                            Address2 = "Apt 8",
                            Address3 = "",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2L,
                            DOB = new DateTime(1987, 8, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Logistics",
                            Email = "henry.gray@example.com",
                            FirstName = "Henry",
                            IsActive = true,
                            JobRole = "Driver",
                            LastModifiedBy = 1,
                            LastName = "Gray",
                            LineManager = "Eve Green",
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Postcode = "EMP8 8HH",
                            Telephone = "07888 888888"
                        },
                        new
                        {
                            Id = 9L,
                            Address1 = "9 Main St",
                            Address2 = "Apt 9",
                            Address3 = "",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3L,
                            DOB = new DateTime(1993, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Admin",
                            Email = "ivy.violet@example.com",
                            FirstName = "Ivy",
                            IsActive = true,
                            JobRole = "Receptionist",
                            LastModifiedBy = 1,
                            LastName = "Violet",
                            LineManager = "Frank Blue",
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Postcode = "EMP9 9II",
                            Telephone = "07999 999999"
                        },
                        new
                        {
                            Id = 10L,
                            Address1 = "10 Main St",
                            Address2 = "Apt 10",
                            Address3 = "",
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1L,
                            DOB = new DateTime(1989, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Facilities",
                            Email = "jack.white@example.com",
                            FirstName = "Jack",
                            IsActive = true,
                            JobRole = "Cleaner",
                            LastModifiedBy = 1,
                            LastName = "White",
                            LineManager = "Grace Brown",
                            ModifiedDate = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            Postcode = "EMP10 0JJ",
                            Telephone = "07000 000000"
                        });
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Manager", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Managers", "crm");
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ContractId")
                        .HasColumnType("bigint");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<long>("ProductTypeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products", "crm");
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.ProductType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ChargeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DefaultPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes", "crm");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ChargeCode = "OHPFULL",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "OHP Full Day",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OHP Full Day",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            ChargeCode = "OHPHALF",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 1000m,
                            Description = "OHP Half Day",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OHP Half Day",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3L,
                            ChargeCode = "OHAFULL",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "OHA Full Day",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OHA Full Day",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4L,
                            ChargeCode = "OHAHALF",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "OHA Half Day",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OHA Half Day",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5L,
                            ChargeCode = "OHTFULLDAY",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "OHT Full Day",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OHT Full Day",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6L,
                            ChargeCode = "OHPAPP",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "OHP Appointment",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OHP Appointment",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7L,
                            ChargeCode = "OHPPENS",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Pensions Case",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pensions Case",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8L,
                            ChargeCode = "OHPAUDIO",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Audiometry Reviews (per 15 mins)",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Audiometry Reviews (per 15 mins)",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9L,
                            ChargeCode = "RETAIN",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Monthly Retainer Fee",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Monthly Retainer Fee",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10L,
                            ChargeCode = "OHPTIME",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "OHP Consultancy Time (per 15 mins)",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OHP Consultancy Time (per 15 mins)",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11L,
                            ChargeCode = "PPHA",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Pre Placement Health Assessment",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pre Placement Health Assessment",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12L,
                            ChargeCode = "PPHA15",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Pre Placement Health Assessment (per 15 mins)",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Pre Placement Health Assessment (per 15 mins)",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13L,
                            ChargeCode = "MTRC",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Mileage and Travel Re-Charged to Customer (per mile)",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mileage and Travel Re-Charged to Customer (per mile)",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14L,
                            ChargeCode = "ARC",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Accommodation Recharged to Customer",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Accommodation Recharged to Customer",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15L,
                            ChargeCode = "CRC",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Consumables Recharged to Customer",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Consumables Recharged to Customer",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16L,
                            ChargeCode = "PSRC",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Physiotherapy Services Recharged to Customer",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Physiotherapy Services Recharged to Customer",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17L,
                            ChargeCode = "GPSR",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "GP / Specialist Report Recharged",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GP / Specialist Report Recharged",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18L,
                            ChargeCode = "ADMIN",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Administration Time",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Administration Time",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19L,
                            ChargeCode = "HAVS1",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "HAVS Tier 1",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HAVS Tier 1",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20L,
                            ChargeCode = "HAVS2",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "HAVS Tier 2",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HAVS Tier 2",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 21L,
                            ChargeCode = "HAVS3",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "HAVS Tier 3",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HAVS Tier 3",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22L,
                            ChargeCode = "HAVS4",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "HAVS Tier 4",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "HAVS Tier 4",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23L,
                            ChargeCode = "OHPFULLCOMPLEX",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "OHP Full Complex",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "OHP Full Complex",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24L,
                            ChargeCode = "PTSMINI",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "PTS / Rail Work mini audit",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PTS / Rail Work mini audit",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 25L,
                            ChargeCode = "PTSPAPER",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "PTS / Rail Work paper based review",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PTS / Rail Work paper based review",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 26L,
                            ChargeCode = "PTSAUDIT",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "PTS / Rail Work audit of cases",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PTS / Rail Work audit of cases",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 27L,
                            ChargeCode = "PTSRETAIN",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "PTS / Rail Work Retainer (per month)",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "PTS / Rail Work Retainer (per month)",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 28L,
                            ChargeCode = "PTSADD",
                            CreatedBy = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultPrice = 85m,
                            Description = "Additional PTS or MRO work or reporting (per 15 mins)",
                            EndTime = new DateTime(2026, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LastModifiedBy = 0,
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Additional PTS or MRO work or reporting (per 15 mins)",
                            StartTime = new DateTime(2025, 4, 16, 17, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Contract", b =>
                {
                    b.HasOne("Server.Modules.CRM.Entities.Customer", null)
                        .WithMany("Contracts")
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Document", b =>
                {
                    b.HasOne("Server.Modules.CRM.Entities.Customer", null)
                        .WithMany("Documents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Manager", b =>
                {
                    b.HasOne("Server.Modules.CRM.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Product", b =>
                {
                    b.HasOne("Server.Modules.CRM.Entities.Contract", null)
                        .WithMany("Products")
                        .HasForeignKey("ContractId");

                    b.HasOne("Server.Modules.CRM.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Contract", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Server.Modules.CRM.Entities.Customer", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
